DatabaseAPI implementation
IdeaSeekers/Calculator-backend pull request #2
Opened 2022-09-12 19:41 UTC by bagrorg

2022-09-12 20:29 UTC, mandelshtamd requested changes
overall it looks nice ;)

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseUsersRepository.cs
> +    // TODO: do we support password change?
i suppose that for this task we don't

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseUsersRepository.cs
> +        int ret = registerCommand.ExecuteNonQuery();
bad variable name

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseHistoryRepository.cs
> +        String insertHistoryString = getInsertHistoryString(value.id, value.query, value.valid, value.result);
better to name this insertHistoryQuery

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseHistoryRepository.cs
> +        int ret = insertHistoryCommand.ExecuteNonQuery();
bad variable name

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseHistoryRepository.cs
> +            int idColumn = 0, queryColumn = 1, validColumn = 2, resultColumn = 3;
Я бы вынес константы в енам и использовал значения из енама, чтобы проще было модифицировать порядок столбцов

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseConnectionProvider.cs
> +        connectionString = "Server=127.0.0.1;" +
ip сервера лучше вынести в отдельную константу. В идеале вообще в какой-нибудь конфиг, но для этого дз это оверинжениринг конечно, так что просто в отдельную константу

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseAPI.cs
> +                if (history[i].valid) result = new CalculationResult(Result.Ok(history[i].result));
было бы удобнее читать, если бы if/else был не в одну строку

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseUsersRepository.cs
> +            int idColumn = 0, loginColumn = 1, passwordColumn = 2;
Я бы вынес константы в енам и использовал значения из енама, чтобы проще было модифицировать порядок столбцов

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseHistoryRepository.cs
> +    public List<HistoryDatabaseRow> Get(Int32 key)
лучше назвать userId

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseHistoryRepository.cs
> +    public Int32 id;
лучше назвать userId, потому что легко подумать, что речь об id записи

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseAPI.cs
> +            if (row.valid) row.result = calculationData.Result.Result.Value;
лучше не делать однострочный if

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseAPI.cs
> +            row.result = -1;
лучше вынести -1 как константу.
public const int BAD_RESULT = -1;

2022-09-12 20:29 UTC, mandelshtamd commented on Database/DatabaseAPI.cs
> +            Int32 id = usersRepo.Get(userInfo).id;
аналогично лучше конкретизировать id чего используется, чтобы в момент использования каждый раз не возвращаться к тому, что было в обьявлении переменной

2022-09-12 20:35 UTC, SBOne-Kenobi commented on Database/DatabaseAPI.cs
> +            usersRepo.Insert(user);
Is the user's existence checked?

2022-09-12 20:37 UTC, SBOne-Kenobi commented on Database/DatabaseUsersRepository.cs
> +        int ret = registerCommand.ExecuteNonQuery();
c++ moment

2022-09-12 20:39 UTC, bagrorg commented on Database/DatabaseAPI.cs
> +            usersRepo.Insert(user);
This is checked at the database level, since the login attribute is unique

2022-09-13 11:06 UTC, IdeaSeeker requested changes

2022-09-13 11:06 UTC, IdeaSeeker commented on Database/DatabaseAPI.cs
> +                if (history[i].Valid) result = new CalculationResult(Result.Ok(history[i].Result));
```suggestion
                if (history[i].Valid)
                    result = new CalculationResult(Result.Ok(history[i].Result));
```

2022-09-13 11:06 UTC, IdeaSeeker commented on Database/DatabaseHistoryRepository.cs
> +        if (ret == -1) throw new NpgsqlException("ExecuteNonQuery() inside insert failed");
```suggestion
        if (ret == -1)
            throw new NpgsqlException("ExecuteNonQuery() inside insert failed");
```

2022-09-13 11:06 UTC, IdeaSeeker commented on Database/DatabaseUsersRepository.cs
> +        if (ret == -1) throw new NpgsqlException("ExecuteNonQuery() inside update failed");
```suggestion
        if (ret == -1)
            throw new NpgsqlException("ExecuteNonQuery() inside update failed");
```

2022-09-15 12:04 UTC, bagrorg commented on Database/DatabaseHistoryRepository.cs
> +            int idColumn = 0, queryColumn = 1, validColumn = 2, resultColumn = 3;
Эти константы имеют локальный характер, в том плане, что они не всегда соответствуют всем колонкам таблицы. `Reader` может содержать меньше колонок и тогда `enum` для всех колонок станет неактуальным. Более того, `enum` приведет к тому что придется явно кастовать значение для `get`-теров, так как они явно требуют `int`, что может привести к лишнему синтаксическому шуму.
Зарезолвите, если убедил

2022-09-15 12:05 UTC, bagrorg commented on Database/DatabaseUsersRepository.cs
> +            int idColumn = 0, loginColumn = 1, passwordColumn = 2;
[Здесь](https://github.com/IdeaSeekers/Calculator-backend/pull/2#discussion_r971899387) ответил на аналогичный комментарий

2022-09-15 12:16 UTC, mandelshtamd approved these changes
хорошая работа

2022-09-15 12:51 UTC, IdeaSeeker approved these changes

2022-09-15 14:15 UTC, merged