Add Calculator API
IdeaSeekers/Calculator-backend pull request #3
Opened 2022-09-13 19:45 UTC by IdeaSeeker

2022-09-13 20:23 UTC, mandelshtamd requested changes

2022-09-13 20:23 UTC, mandelshtamd commented on UnitTest/CalculatorTest.cs
> +            var actual = CalculatorAPI.Calculate(new CalculationQuery(userInput));
начиная с какого значения calculate будет возвращать Infinity? когда не вмещается в double?

2022-09-13 20:23 UTC, mandelshtamd commented on UnitTest/CalculatorTest.cs
> +            Console.WriteLine(actual.Result.ToString());
лишний writeLine, лучше убрать

2022-09-13 20:23 UTC, mandelshtamd commented on Calculator/CalculatorAPI.cs
> +            var result = expression.calculate();
ошибку с некорректным синтаксисом в catch ловим?

2022-09-13 20:23 UTC, mandelshtamd commented on UnitTest/CalculatorTest.cs
> +    public class Tests
Думаю, не стоит тесты на проверку вычислений размещать в классе Tests. Так как у нас много модулей, каждый из которых нужно протестировать, то лучше тесты для каждого из модулей размещать в отдельном тестовом классе, название которого будет отражать то, что тестируется. Соответственно для вычислений тестовый класс лучше переименовать в какой-нибудь CalculationsTest и переименовать файл на такое же название

2022-09-13 20:23 UTC, mandelshtamd commented on Calculator/CalculatorAPI.cs
> +    public static CalculationResult Calculate(CalculationQuery query)
не будет проблем с многопоточностью?

2022-09-13 20:23 UTC, mandelshtamd commented on Calculator/CalculatorAPI.cs
> +        return userInput.Replace("log", "log10");
Плохо, что CalculatorAPI делает не свою работу. Лучше либо договориться, что с фронта приходит выражение в правильном формате, либо обрабатывать перед вызовом Calculate в вызывающем коде

2022-09-14 10:41 UTC, IdeaSeeker commented on UnitTest/CalculatorTest.cs
> +            var actual = CalculatorAPI.Calculate(new CalculationQuery(userInput));
да

2022-09-14 10:41 UTC, IdeaSeeker commented on UnitTest/CalculatorTest.cs
> +            Console.WriteLine(actual.Result.ToString());
упс)

2022-09-14 10:41 UTC, IdeaSeeker commented on Calculator/CalculatorAPI.cs
> +            var result = expression.calculate();
некорректный синтаксис - это NaN

2022-09-14 10:43 UTC, IdeaSeeker commented on Calculator/CalculatorAPI.cs
> +        return userInput.Replace("log", "log10");
Во-первых, мы так договорились с Рустамом. Во-вторых, вызывающий код не должен знать о деталях реализации, в частности о библиотеке mxparser

2022-09-14 10:44 UTC, IdeaSeeker commented on Calculator/CalculatorAPI.cs
> +    public static CalculationResult Calculate(CalculationQuery query)
А какие проблемы? У статического класса нет состояния даже

2022-09-14 10:46 UTC, IdeaSeeker commented on UnitTest/CalculatorTest.cs
> +    public class Tests
файл итак правильно называется, а класс почему-то нет... Си шарп)

2022-09-14 11:03 UTC, bagrorg reviewed
LGTM, только стоит пофиксить `\n` в конце файлов

2022-09-14 11:03 UTC, bagrorg commented on Calculator/CalculatorAPI.cs
> +            return new CalculationResult(Result.Fail(e.Message));
Возможно стоит указать источник ошибки, по одному лишь сообщению не всегда очевидно, где возникла проблема

2022-09-14 20:03 UTC, IdeaSeeker commented on Calculator/CalculatorAPI.cs
> +            return new CalculationResult(Result.Fail(e.Message));
Что такое источник ошибки? Конкретное место в выражении? Если да, то полностью с тобой согласен, но апи библиотеки так делать не позволяет, поэтому предлагаю не делать лишних усложнений :)

2022-09-14 20:39 UTC, bagrorg commented on Calculator/CalculatorAPI.cs
> +            return new CalculationResult(Result.Fail(e.Message));
API библиотеки позволяет вызвать `e.Source`. Если кажется, что это излишне -- ок

2022-09-15 12:53 UTC, mandelshtamd approved these changes

2022-09-15 13:29 UTC, merged